# Generated by Django 5.1.6 on 2025-02-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocClassifier', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
