# Generated by Django 5.1.6 on 2025-02-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocClassifier', '0003_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
