# Generated by Django 5.1.5 on 2025-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFOperationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('merge', 'Merge'), ('compress', 'Compress'), ('split', 'Split'), ('searchable', 'Convert to Searchable'), ('redact', 'Redact'), ('pdf_to_docx', 'PDF to DOCX')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
