# Generated by Django 5.1.5 on 2025-02-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='text',
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='text_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=models.BinaryField(),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DocChat.uploadeddocument'),
            preserve_default=False,
        ),
    ]
