name: Deploy to VPS

on:
  push:
    branches:
      - main 
      - Chitwan-Dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: documentmanager
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /home/documentmanager/htdocs/documentmanager.ai/deploy.sh
