name: docker-deploy

on:
  push:
    branches:
      - main   # change to main when you're ready for production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/documentmanager-web:latest ./DocumentManager

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/documentmanager-web:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/documentmanager
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            systemctl restart nginx
            echo "Deployment successful!"
